store_manager/store_app/urls.py
from django.contrib import admin
from django.urls import path


from .views import (
    StoreListView,
    StoreDetailView,
    StoreCreateView,
    StoreUpdateView,
    StoreDeleteView,
)

app_name = "store"

urlpatterns = [
    path("", StoreListView.as_view(), name="all"),
    path("create/", StoreCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", StoreDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", StoreUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", StoreDeleteView.as_view(), name="delete"),
]


# -> a la urls.py del project


# router


from .router import router

urlpatterns += router.urls

store_manager/store_manager/urls.py
from django.contrib import admin
from django.urls import path , include

from .views import Index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Index.as_view(), name="index"),
    path("store/", include("store_app.urls")),
]

store_manager/store_app/models.py
from django.db import models
from django.db.models import Model


# Create your models here.
class Store(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """

    nombre = models.CharField(max_length=100, default="Cerveza X")
    estilo = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    cantidad_disponible = models.IntegerField(default=0)
    fecha_habilitacion = models.DateField(auto_now=True)
    

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
        db_table = "Cervezas"

    def __str__(self):
        return f"Cervezas: {self.nombre}"

    def get_fields(self):
        """
         Obtiene los nombres y valores de los campos de un modelo.

        Retorna una lista de tuplas donde cada tupla contiene el nombre descriptivo del campo
        y el valor correspondiente para el objeto actual.

        :return: Lista de tuplas (nombre del campo, valor del campo)
        :rtype: list
        """
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]


# -> paso siguiente  -> admin.py

store_manager/store_app/views.py
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView


from .models import Store

# Create your views here.


class StoreBaseView(View):
    template_name = "store.html"
    model = Store
    fields = "__all__"
    success_url = reverse_lazy("store:all")


class StoreListView(StoreBaseView, ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Store
    """


class StoreDetailView(StoreBaseView, DetailView):
    template_name = "store_detail.html"


class StoreCreateView(StoreBaseView, CreateView):
    template_name = "store_create.html"
    extra_context = {"tipo": "Crear"}


class StoreUpdateView(StoreBaseView, UpdateView):
    template_name = "store_create.html"
    extra_context = {"tipo": "Actualizar"}


class StoreDeleteView(StoreBaseView, DeleteView):
    template_name = "store_delete.html"
    extra_context = {"tipo": "Borrar"}


# -> store_app.urls.py

store_manager/store_manager/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    extra_context = {"comision": "23507"}
    template_name = "index.html"

store_manager/store_app/templates/store.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div>
      <h2>Nuestras cervezas</h2>
      <h2><a href="{% url 'store:create' %}">Crear una cerveza</a></h2>
      <div class="list">
        {% for store in store_list %}
        <div>
          
        <table>

          <tr>
        
            <th>Nombre</th>
        
            <th>Estilo</th>
        
            <th>Precio</th>

            <th>Stock</th>

            <th>Fecha habilitacion</th>

            <th>Acciones</th>
        
          </tr>
        
          <tr>
        
            <td>{{store.nombre}}</td>
        
            <td>{{store.estilo}}</td>
        
            <td>{{store.precio}}</td>

            <td>{{store.cantidad_disponible}}</td>
            
            <td>{{store.fecha_habilitacion}}</td>

            <td><div>
              <label for="">Detalles: </label>
              <a href="{% url 'store:detail' store.id  %}">🟢</a>
            </div>
            <div>
              <label for="">Borrar: </label>
              <a href="{% url 'store:delete' store.id %}">❌</a>
            </div>
            <div>
              <label for="">Editar: </label>
              <a href="{% url 'store:update' store.id %}">📋</a>
            </div></td>
        
          </tr>
      
        </table>

      <div>
        {% endfor %}
      </div>
  
    </div>
  </main>
{% endblock %}

store_manager/store_app/templates/store_create.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
<main>
  <div>
    <form method="post">
      {% csrf_token %}
      {{form.as_div}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'store:all' %}">Volvamos al Inicio</a>
  </div>
</main>
{% endblock %}

store_manager/store_app/templates/store_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
  <div>
    <h2>Estas seguro que deseas borrar esta cerveza?</h2>
    <h2>{{store.nombre}}</h2>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="{{ tipo }}" />
    </form>

    <a href="{% url 'store:all' %}">Cancelar</a>
  </div>
</main>

{% endblock %}

store_manager/store_app/templates/store_detail.html
{% extends 'base.html' %} 
{% block content %}

<main>
  <div>
    <h1>{{store.nombre}}</h1>
    {% for label, value in store.get_fields %}
    <div>
      <span>{{label | upper}}</span>
      <span> <b> {{value}} </b></span>
    </div>

    {% endfor %}

    <a href="{% url 'store:all' %}">Ir al inicio</a>
  </div>
</main>

{% endblock%}

store_manager/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{% static './css/style.css' %}" />
  <link rel="stylesheet" href="{% static './css/formulario.css' %}" />
  <link rel="stylesheet" href="{% static './css/style1.css' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" crossorigin="anonymous">
  <title>Cervecería CreArte</title>
</head>

<body>
  <div class="loader">
    <div class="balls"></div>
  </div>

  <header class="header" id="header">
    <nav class="navbar">
      
      <div class="burger" id="burger">
        <span class="burger-line"></span>
        <span class="burger-line"></span>
        <span class="burger-line"></span>
      </div>
      <span class="overlay"></span>
      <div class="menu" id="menu">
        <ul class="menu-inner">
          <li class="menu-item">
            <a class="menu-link" href="{% url 'index' %}">Inicio</a>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="{% url 'store:all' %}">CRUD Cervezas</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>


  
 

  {% block content %} {% endblock %}
</body>
<script src=" https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js "></script>
<script src="{% static './js/index.js' %}"></script>

</html>

store_manager/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<section class="inicio">
       
    <div class="containerInicial">
        <div class="containerImagen">
            <div><img class="imagenInicio" src="{% static './imgs/imageninicial1.jpg' %}" alt="ups"></div> 
            <h2 class="textoInicial">Cerveceria Crearte</h2>
        </div>

        <div>
            <video  class="videito" muted  id="video1">
                <source src="{% static './videos/beer_-_59600 (1080p).mp4' %}" type="video/mp4">
            </video>

            <audio id="musica1">
                <source src="{% static './audios/salamisound-1020037-pour-beer-from-a-bottle.mp3' %}" type="audio/mpeg">
            </audio>

        </div>
        
    </div>

    <div></div>
</section>


    
    <section class="nosotros1"  id="nosotros">
        <div class="cointanerInicial">
           <div class="textonosotros">
                <div>
                    
                    <h2>CreArte</h2>
                    <br>
                   
                    <p>"Fundada con pasión y un profundo amor por la cerveza, nuestra cervecería es un rincón de tradición 
                        cervecera que ha prosperado a lo largo de los años. Desde sus modestos inicios en 2007,
                         hemos trabajado incansablemente 
                        para ofrecer a nuestros clientes una experiencia única en cada vaso.
                        En cada rincón de nuestra cervecería, se respira la historia y la dedicación que hemos invertido en este viaje. Nuestro compromiso con la excelencia se refleja en cada lote de cerveza que producimos. Desde 
                        las cervezas de malta más robustas hasta las cervezas ligeras y refrescantes, ofrecemos una variedad que satisface a todos los gustos.
                        Ven y únete a nosotros en este emocionante viaje cervecero. Ya sea que seas un conocedor de la cerveza o simplemente estés buscando una experiencia única, te invitamos a compartir nuestra pasión por la cerveza en nuestra cervecería, donde la tradición se encuentra con la innovación en cada sorbo. 
                        ¡Esperamos verte pronto en CreArte cerveceria!"
                    </p>
                    
                    </div>
                    <br>
                    
                    <div><img class="img1" src="{% static './imgs/cabecera-cerveza.avif' %}"></div>
                <div>
            </div>
              
        </div>
    </section>
    
    <br>

    <section class="promociones1" id="promociones">
        <div class="container1 textonosotros">
            
            <h2>Promociones</h2>
            <br>
            <br>
            <p>Compra una selección de nuestras cervezas premium y recibe un descuento especial en cada botella o lata. ¿Eres un amante de la cerveza artesanal? ¡Estás de suerte!
               Nuestra promoción también incluye nuestras creaciones más innovadoras y experimentales.
            </p>
            <br>

            <div class="containerPromos">
                <div class="containers">
                    <br>
                    <div class="imagencerveza">
                        <img class="img1" src="{% static './imgs/1.png' %}">
                    </div>

                    <div class="texto">
                        <h5>Pinta red</h5>
                        <p>Este tipo de cerveza se caracteriza por su color, que varía de un tono ámbar a rojo profundo, y suele tener un sabor y 
                            aroma maltoso con toques de caramelo y tostado.
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>

                </div>

                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/2.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Rubia</h5>
                        <p>Se caracteriza por tener un color dorado o amarillo claro. Suele ser refrescante y tiene un sabor equilibrado, con notas maltosas 
                            y un toque de amargura que varía según el estilo y la marca
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>

                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/3.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Double</h5>
                        <p>Variedad popular de cerveza mixta que a menudo se hace mezclando cerveza con limonada o soda de limón, lo que resulta en una bebida refrescante 
                            y efervescente con un sabor cítrico
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>

                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/4.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Porter</h5>
                        <p>Se caracteriza por tener sabores y aromas muy pronunciados y a menudo una mayor concentración 
                            de alcohol en comparación con las cervezas más suaves.
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>


                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/5.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Saison</h5>
                        <p>Una cerveza Saison, también conocida como Farmhouse Ale, es un estilo de cerveza belga que 
                            se caracteriza por su frescura y carácter refrescante.
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>


                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/6.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Blonde</h5>
                        <p> Blonde IPA es un subestilo de India Pale Ale (IPA) que se caracteriza por su perfil de sabor
                            equilibrado y su aspecto más claro en comparación con algunas otras IPAs.
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>


                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/7.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Ipa Ale</h5>
                        <p>Se destaca por su sabor amargo y su abundante aroma a lúpulo.
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
                </div>


                <div class="containers">
                    <br>
                    <div>
                        <img class="img1" src="{% static './imgs/8.png' %}">
                    </div>
                    <div class="texto">
                        <h5>Sour Ale</h5>
                        <p>Es un estilo de cerveza que se caracteriza por tener un sabor ácido o agrio. Estas cervezas se obtienen mediante la 
                            fermentación con cepas de levadura 
                        </p>
                        <br>
                        <div class="botoncompra">
                            <button id="add-to-cart-1">Agregar al carrito</button>
                        </div>
                    </div>
            
                </div>
            
            </div>
        </div>

    </section>


           


 
<footer class="footer" id="contacto">
        
    <div class="container3">
        <div class="footer-row">

            <div class="footer-links">
                
                <section id="formSec" class="formSec">
                    <form action="https://sheetdb.io/api/v1/swbypo2ko8wyt" method="POST" id="sheetdb-form">
                      <h3>Consultas</h3>
          
                        <div class="form">
                          <label for="name">Nombre y Apellido:</label>   
                          <div id="error-name"></div>
                          <input type="text" id="name" name="data[name]" class="claseFormulario" onkeyup="validate()"/>
                        </div>
          
                        <div class="form">
                          <label for="email">Email:</label>
                          <div id="error-email"></div>
                          <input type="email" id="email" name="data[email]" class="claseFormulario"  onkeyup="validate()"/>
                        </div>
          
                        <div class="form">
                          <label for="comentario">Mensajes:</label>
                          <div id="error-comentario"></div>
                          <textarea id="comentario" name="data[comentario]" rows="10" class="claseFormulario"  onkeyup="validate()"></textarea>
                        </div>
                      
                       
                        <div class="form">
                          <button type="submit" id="submit" class="enviar">Enviar!</button>
                        </div>
          
                    </form>
                  </section>
                  
              </div>


            <div class="footer-links">
              <h4>Contacto</h4>
                <ol>
                    <li><h5>Teléfono</h5> </li>
                    <li><h5>(+123)4567 4534</h5> </li>
                </ol>

                <br>
                <br>

              <h4>Siguenos</h4>
                <div>
                   <ol>
                     <a href="https://www.facebook.com/?locale=es_LA"><i class="fab fa-facebook-f"></i></a>
                     <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                     <a href="https://twitter.com/?lang=es"><i class="fab fa-twitter"></i></a>
                    </ol>
                </div>
            </div>

            <div class="footer-links">
                <h4>Ubicación</h4>
                <div class="mapa">
                    <li><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d821.5796750683584!2d-58.45998977155011!3d-34.54548529830391!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb426cfb55dc7%3A0x597e74d62bbc0bf2!2sNu%C3%B1ez%201511%2C%20C1429%20CABA!5e0!3m2!1ses-419!2sar!4v1696517916131!5m2!1ses-419!2sar" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></li>
                </div>
            </div>
           
        </div>
      
    </div>
    <br>
    <br>
    <br>
    <div class="by"><p>&copy; CreArte 2023 </p></div>
</footer>

<script src="{% static './js/cerveceria.js' %}"></script>


<script src="{% static './js/form.js' %}"></script>




{% endblock %}